# Configurazione Brevo
api.key=xxxxxxx
sender.email=safedrivemonitor@gmail.com
sender.name=SafeDriveMonitor
api.key.sms="inserire api"//attualmente funziona ma non abbiamo comprato crediti per gli sms